name: $(BuildID)
trigger:
  branches:
    include:
      - master
      - renovate/*

jobs:
  - job: lint
    pool:
      vmImage: ubuntu-16.04
    steps:
      - powershell: ./build.ps1
        displayName: Build assemblies
      - powershell: |
          $ProgressPreference = 'SilentlyContinue'
          Install-Module -Force -Scope CurrentUser PSScriptAnalyzer
          Get-ChildItem -Recurse -File -Filter '*.ps1' | Invoke-ScriptAnalyzer -Settings ./PSScriptAnalyzerSettings.psd1 | Format-List -Property RuleName,Message,ScriptPath,Line,Column
        displayName: Run PSScriptAnalyzer
  - template: .vsts/template.yml
    parameters:
      name: test_linux
      vmImage: ubuntu-16.04
  - template: .vsts/template.yml
    parameters:
      name: test_macos
      vmImage: macOS-10.14
  - template: .vsts/template.yml
    parameters:
      name: test_windows
      vmImage: windows-2019
  - job: release
    pool:
      vmImage: ubuntu-16.04
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    dependsOn:
      - test_linux
      - test_macos
      - test_windows
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: ^10.3.0
      - bash: npm ci && ./node_modules/.bin/semantic-release
        env:
          NUGET_API_KEY: $(NuGetApiKey)
          GITHUB_TOKEN: $(GitHubToken)
        displayName: Run semantic-release
