parameters:
  name: ''
  queue: ''

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
      - script: |
          git config --global user.name "GIVEN_NAME SURNAME"
          git config --global user.email "email@example.com"
        displayName: Configure git user
      - powershell: ./build.ps1
        displayName: Build assemblies
      - powershell: |
          $ProgressPreference = "SilentlyContinue"
          $PSVersionTable
          Install-Module -Force -Scope CurrentUser -SkipPublisherCheck Pester -RequiredVersion '4.4.3'
          Install-Module -Force -Scope CurrentUser PSCodeCovIo
          $res = Invoke-Pester -PassThru -CodeCoverage PowerGit/Functions/*.ps1 -CodeCoverageOutputFile coverage.xml -OutputFile testresults.xml
          if ($res.TotalCount -eq 0) {
            throw "No tests"
          }
          Export-CodeCovIoJson -CodeCoverage $res.CodeCoverage -RepoRoot $pwd -Path coverage.json
          if ($res.FailedCount -gt 0) {
            throw "$($res.FailedCount) tests failed."
          }
        displayName: Run tests
      - task: PublishTestResults@2
        inputs:
          testRunner: nUnit
          testResultsFiles: 'testresults.xml'
          testRunTitle: ${{ parameters.name }}
        condition: always()
        displayName: Publish test results
      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: JaCoCo
          summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage.xml
        displayName: Upload coverage to VSTS
      - bash: bash <(curl -s https://codecov.io/bash) -f coverage.json -P "$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER"
        env:
          CI_BUILD_ID: $(Build.BuildNumber)-$(Agent.OS)
          CODECOV_NAME: ${{ parameters.name }}
          VCS_BRANCH_NAME: $(Build.SourceBranchName)
          VCS_COMMIT_ID: $(Build.SourceVersion)
          CODECOV_TOKEN: $(CodeCovToken)
        displayName: Upload coverage to CodeCov
